<?php
DEFINE("_SHOP_ITEM1",    			        "Поени за напад");
DEFINE("_SHOP_ITEM2",    			        "Банкарска сметка");
DEFINE("_SHOP_ITEM3",    			        "Заштита од мафијата");
DEFINE("_SHOP_ITEM4",    			        "Безбол палка");
DEFINE("_SHOP_ITEM5",    			        "Солзавец");
DEFINE("_SHOP_ITEM6",    			        "Џебен нож");
DEFINE("_SHOP_ITEM7",    			        "Питбул");
DEFINE("_SHOP_ITEM8",    			        "Sig P228");
DEFINE("_SHOP_ITEM9",    			        "Desert Eagle");
DEFINE("_SHOP_ITEM10",    			        "Узи");
DEFINE("_SHOP_ITEM11",    			        "Телохранители");
DEFINE("_SHOP_ITEM12",    			        "Автоматска пушка M-16");
DEFINE("_SHOP_ITEM13",    			        "AK-47 Калашников");
DEFINE("_SHOP_ITEM14",    			        "Снајпер");
DEFINE("_SHOP_ITEM15",    			        "RPG");
DEFINE("_SHOP_ITEM16",    			        "Бомба C4");
DEFINE("_SHOP_ITEM17",    			        "Тенк");
DEFINE("_SHOP_ITEM18",    			        "Воен брод");
DEFINE("_SHOP_ITEM19",    			        "Ракета 'Скад'");
DEFINE("_SHOP_ITEM20",    			        "Атомска бомба");
DEFINE("_SHOP_ITEM21",    			        "Сателит");
DEFINE("_SHOP_ITEM22",    			        "Вселенска станица");
DEFINE("_SHOP_ITEM23",    			        "Кафетерија");
DEFINE("_SHOP_ITEM24",    			        "Сеф");
DEFINE("_SHOP_ITEM25",    			        "Банкарска сметка во Швајцарија");
DEFINE("_SHOP_ITEMINFO1",    			    "");
DEFINE("_SHOP_ITEMINFO2",    			    "");
DEFINE("_SHOP_ITEMINFO3",    			    "");
DEFINE("_SHOP_ITEMINFO4",    			    "");
DEFINE("_SHOP_ITEMINFO5",    			    "");
DEFINE("_SHOP_ITEMINFO6",    			    "");
DEFINE("_SHOP_ITEMINFO7",    			    "");
DEFINE("_SHOP_ITEMINFO8",    			    "");
DEFINE("_SHOP_ITEMINFO9",    			    "");
DEFINE("_SHOP_ITEMINFO10",    			    "");
DEFINE("_SHOP_ITEMINFO11",    			    "");
DEFINE("_SHOP_ITEMINFO12",    			    "");
DEFINE("_SHOP_ITEMINFO13",    			    "");
DEFINE("_SHOP_ITEMINFO14",    			    "");
DEFINE("_SHOP_ITEMINFO15",    			    "");
DEFINE("_SHOP_ITEMINFO16",    			    "");
DEFINE("_SHOP_ITEMINFO17",    			    "");
DEFINE("_SHOP_ITEMINFO18",    			    "Со сателит можеш да ја следиш локацијата на конкретен мафијаш.");
DEFINE("_SHOP_ITEMINFO19",    			    "Од вселенската станица можеш да гледаш кој каде се наоѓа во моментот.");
DEFINE("_SHOP_ITEMINFO20",    			    "Започни легален бизнис. Отвори венец од ресторани и земај по 500 € час додека другите работат.");
DEFINE("_SHOP_ITEMINFO21",    			    "Сефот има предност во тоа што парите во него се засекогаш на сигурно,<br> дури и да си нападнат или мртов. Никој од другите <br>корисници не може да гледа кој колку пари има во сефот,<br> а секој сеф собира по 50 милиони евра за кои што не добиваш камата.");
DEFINE("_SHOP_ITEMINFO22",    			    "Предност на Швајцарските банки е тоа што сметките во нив и целата <br>информација за нив се чуваат во тајност. Ако си направиш <br>сметка таму ќе можеш да депозираш по 5 милиони и да <br>подигаш 50 милиони евра на ден. Каматата на ден е 2%.");
DEFINE("_SHOP_ITEMINFO23",    			    "Ти требаат само 5 поени за да ги напаѓаш другите мафијаши.");
DEFINE("_SHOP_ITEMINFO24",    			    "Отвори си банкарска сметка во некоја банка и осигурај ги твоите пари.<br> Со отварањето на банкарска сметка ќе бидеш <br>во можност да извршуваш легални трансакции на пари.");
DEFINE("_SHOP_ITEMINFO25",    			    "Се плашиш? Купи заштита од мафијата и спиј мирно. <br>На располагање ти стои 24 часовна заштита од <br>поранешни членови на специјалната единица на армијата.<br> Искористи ја мудро нивната заштита.");
?>