<?php
/*================================= CARS  ==========================================*/
DEFINE("_CARS_GO",	    			    "Ukradi kola");
DEFINE("_CARS_TAB1",	   			    "Srednja klasa");
DEFINE("_CARS_TAB2",	   			    "Brza klasa");
DEFINE("_CARS_TAB3",	   			    "Top 5");
DEFINE("_CARS_PRICE",	    			"Cena");
DEFINE("_CARS_CHANCE",			    	"Šansa");
DEFINE("_CARS_MAX_SPEED",				"Maks. brzina");
DEFINE("_CARS_MAX_SPEED_PREFIX",		"km/h");
DEFINE("_CARS_PASSENGERS",				"broj mesta");
DEFINE("_CARS_PASSENGERS_PREFIX",		"mesta");
DEFINE("_CARS_HP",			         	"Moć");
DEFINE("_CARS_HP_PREFIX",				"k.s.");
DEFINE("_CARS_TITLE",                   "kradja kola");
DEFINE("_CARS_BEHIND1",                 "policija je iza tebe, posle ");
DEFINE("_CARS_BEHIND2",                 "možeš ponovo da preuzmeš akciju");
DEFINE("_CARS_INFO",                    "Imaš mogućnost da kradeš kola. Koliko ti je veći rang, toliko većca verovatoća da odeš kući sa nova kola.");
DEFINE("_CARS_DONE",				    "ti si uspeo da ukradeš kola!<br> možeš da je vidiš u garaži");
DEFINE("_CARS_FAIL",				    "Dok si pokušavao da ukradeš kola, prošla je patrola i policija te videla. Srećom trčao si brzo i uspeo si da im pobegneš");
DEFINE("_CARS_JAIL",				    "Pokušavajući da uradeš kola, policija te videla i opkolila! Već si u zatvoru!");
DEFINE("_CAR1",							"Opel vectra 1.8i");
DEFINE("_CAR2",							"Toyota Prius");
DEFINE("_CAR3",							"Volvo S40");
DEFINE("_CAR4",							"VW Golf VI");
DEFINE("_CAR5",							"Alfa Romeo Brera");
DEFINE("_CAR6",							"Ford Mondeo");
DEFINE("_CAR7",							"VW Passat");
DEFINE("_CAR8",							"Mercedes-Benz CLK 200 Compressor");
DEFINE("_CAR9",							"Subaru Impreza WRX");
DEFINE("_CAR10",						"Mitsubishi Lancer EVO9");
DEFINE("_CAR11",						"Nissan Skyline GTR");
DEFINE("_CAR12",						"Audi RS6");
DEFINE("_CAR13",						"Audi S8");
DEFINE("_CAR14",						"Porsche Carrera GT");
DEFINE("_CAR15",						"Ferrari F430 Scuderia");
DEFINE("_CAR16",						"Lamborghini Murciélago");
DEFINE("_CAR17",						"Mercedes-Benz SLR McLaren");
DEFINE("_CAR18",						"Bugatti Veyron");
?>