<?php

/*=================================  LOGIN  ==========================================*/
DEFINE("_REGISTRATION_COMPLETE",		"<h3>Вашата регистрация е успешнана.</h3> Моля проверете си пощата за да активирате акаунта.<br><br>Приятна игра!<br>");
DEFINE("_REGISTRATION_IP_ERROR",		"Грешка! Вашият IP адреса е регистриран вече.<br>Позволение са по 2 регистрации от един ИП адрес.");
DEFINE("_REGISTRATION_EMAIL_ERROR",		"Въведеният и-мейл вече се използва.");
DEFINE("_REGISTRATION_EMAIL_ERROR2",	"Въвели сте грешен имейл. <br>Опитайте отново.");
DEFINE("_REGISTRATION_USERNAME_ERROR",	"Потебителското име е заето.");
DEFINE("_REGISTRATION_USERNAME_ERROR2",	"Потребителското име съдържа непозволени символи. Позволение са само големи и малки латински букви, цифри и знаците .-_");
DEFINE("_REGISTRATION_USERNAME_ERROR3",	"Не сте въвели име.");
DEFINE("_REGISTRATION_PASS_ERR",	    "Не сте въвели парола.");
DEFINE("_REGISTRATION_PASS_ERR2",	    "Паролите не съвпадат.");
DEFINE("_REGISTRATION_CODE_ERR",	    "Въвели сте грешен код. Опитайте отново.");
DEFINE("_REGISTRATION_NOT_ACC",	        "За да се регистирате трябва да сте съгласни с правилата на играта и да сте над 18 години.");
DEFINE("_REG_INFO_BAD_LANG",	        "Играта съдържа груб език");
DEFINE("_REG_INFO_GAMBLING",	        "В играта има <br> хазарт.");
DEFINE("_REG_INFO_DRUGS",   	        "В играта има <br> наркотици");
DEFINE("_REG_INFO_VIOLENCE",	        "Играта съдържа <br>изрази на насилие");
DEFINE("_MAIN_USERNAME",				"Потребителско име");
DEFINE("_MAIN_PASS",				    "Парола");
DEFINE("_MAIN_RE_PASS",				    "Повтори паролата");
DEFINE("_MAIN_EMAIL",				    "Е-мейл адрес");
DEFINE("_MAIN_CAPTACHA",				"Въведи кода");
DEFINE("_MAIN_LOST_PASSWORD",			"Забравена парола?");
DEFINE("_MAIN_USERNAME_TIP",			"Напишете Вашето потр. име.");
DEFINE("_MAIN_PASSWORD_TIP",     		"Напишете Вашата парола.");
DEFINE("_REG_TITLE",		        	"Влезте в света на мафията - WWW.MAFIA.BG");
DEFINE("_REG_KEYWORDS",		        	"регистрация,MAFIA.BG,регистрирай се,онлайн,игра,дрога,алкохол,респект,оръжие,мафия,българска,mafia");
DEFINE("_REG_DESCRIPTION",		        "Регистрирайте се и влезте в светът на мафията. Завладейте света и станете един от най-добрите играчи!");
DEFINE("_REG_ALGIMENT",			        "Съгласен съм с <u>правилата</u> и <u>условията</u> на<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; играта и съм над 18 години");
DEFINE("_LOGIN",                        "Влез в играта!");
DEFINE("_REG_TEAM",                     "<h2>Тимът на MAFIA.BG</h2>");
DEFINE("_REG_NAME_DESC",                "Изберете вашето потр. име. С това име ще се представяте пред другите мафиоти. Вашите лични данни си остават тайна.");
DEFINE("_REG_EMAIL_DESC",               "Въведете вашият е-мейл. На нея ще получите информация за активиране на профила. Вашият имейл остава тайна за другите играчи.");
DEFINE("_REG_PASS_DESC",                "Парола с която ще влизате в играта");
DEFINE("_REG_REPASS_DESC",              "Повторение на паролата");
DEFINE("_LOST_SUCESS1",                 "<h3>Паролата е успешно променена.</h3> Новата парола на потребителя <b>");
DEFINE("_LOST_SUCESS2",                 "</b> е изпратена на: <b>");
DEFINE("_LOST_SUCESS3",                 " </b><br><br>Проверете вашият е-мейл, и ако в срок от 5-10 мин. не пристигне писмо с информация за рестартиране на паролата опитайте повторно или се свържете с администратор.<br><br>Желаем ви приятна игра.");
DEFINE("_LOST_ERROR1",                  "Упсс... има грешка.");
DEFINE("_LOST_ERROR2",                  "Упсс... има грешка. Данните не съвпадат.");
DEFINE("_LOST_ERROR3",                  "Потребителят не съществува...");
DEFINE("_LOST_ERROR4",                  "Въвели сте грешен код. Моля опитайте отново.");
DEFINE("_LOST_ERROR5",                  "Не сте въвели име / парола...");
DEFINE("_LOST_TITLE",                   "MAFIA.BG - Форма за нова парола");
DEFINE("_LOST_KEYWORDS",		        "парола,MAFIA.BG,забравена,рестартиране,и-мейл");
DEFINE("_LOST_DESCRIPTION",		        "Забравихте вашата парола? Рестартирайте я от тук.");
DEFINE("_MAIN_KEYWORDS",		        "www.mafia.bg,MAFIA.BG,mafia,масова,онлайн,гангстерска,игра,респект,оръжие,мафия,българска");
DEFINE("_MAIN_DESCRIPTION",		        "Влезте в света на мафията и започнете да играете най-новата Българска онлайн гангстерска игра!MAFIA.BG! Получете уважението което заслужавате!");
DEFINE("_MAIN_REMEMBER",                "Запомни ме");
DEFINE("_MAIN_REG_INFO",                "Ако още не сте част от мафиотският свят, регистрирайте се тук.");
DEFINE("_MAIN_CC",                      "© 2010 <strong>MAFIA.BG</strong>. Всички права са запазени");
DEFINE("_MAIN_START",                   "Начало");
DEFINE("_MAIN_BETA",                    "Бета сървър");
DEFINE("_MAIN_END",                     "Край");
DEFINE("_MAIN_SEASON",                  "Сезон");
DEFINE("_MAIN_WRONGPASS",               "Грешна парола!<br>Опитайте отново");
DEFINE("_MAIN_REC",                     "ви препоръчваме");
DEFINE("_MAIN_DONE",                    "<h3>Честито</h3>Вашият профил беше успешно активиран.<br>Сега можете да влезнете в света на мафията.");
DEFINE("_MAIN_NOT_ACTIVE",              "Вашият мафиот още не е активиран.<br>Проверете си пощата за упътване как да го направите.");
DEFINE("_MAIN_LOGIN_ERR",               "Въвели сте невалидна информация.<br>Моля опитайте отново.");
DEFINE("_MAIN_TRAILER",                 '<object width="400" height="224" ><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://www.facebook.com/v/1181659018008" /><embed src="http://www.facebook.com/v/1181659018008" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="400" height="224"></embed></object>');
?>