<?php
DEFINE("_SHOP_ITEM1",    			        "Точки за атака");
DEFINE("_SHOP_ITEM2",    			        "Банкова сметка");
DEFINE("_SHOP_ITEM3",    			        "Защита от мафията");
DEFINE("_SHOP_ITEM4",    			        "Бейзболна бухалка");
DEFINE("_SHOP_ITEM5",    			        "Сълзотворен спрей");
DEFINE("_SHOP_ITEM6",    			        "Нож");
DEFINE("_SHOP_ITEM7",    			        "Питбул");
DEFINE("_SHOP_ITEM8",    			        "Sig P228");
DEFINE("_SHOP_ITEM9",    			        "Desert Eagle");
DEFINE("_SHOP_ITEM10",    			        "Узи");
DEFINE("_SHOP_ITEM11",    			        "Телохранители");
DEFINE("_SHOP_ITEM12",    			        "Автоматична пушка M-16");
DEFINE("_SHOP_ITEM13",    			        "AK-47 Калашников");
DEFINE("_SHOP_ITEM14",    			        "Снайпер");
DEFINE("_SHOP_ITEM15",    			        "RPG");
DEFINE("_SHOP_ITEM16",    			        "Бомба C4");
DEFINE("_SHOP_ITEM17",    			        "Танк");
DEFINE("_SHOP_ITEM18",    			        "Боен кораб");
DEFINE("_SHOP_ITEM19",    			        "Ракета 'Скъд'");
DEFINE("_SHOP_ITEM20",    			        "Атомна бомба");
DEFINE("_SHOP_ITEM21",    			        "Сателит");
DEFINE("_SHOP_ITEM22",    			        "Спътник");
DEFINE("_SHOP_ITEM23",    			        "Кафене");
DEFINE("_SHOP_ITEM24",    			        "Сейф");
DEFINE("_SHOP_ITEM25",    			        "Банкова сметка в Швейцария");
DEFINE("_SHOP_ITEMINFO1",    			    "");
DEFINE("_SHOP_ITEMINFO2",    			    "");
DEFINE("_SHOP_ITEMINFO3",    			    "");
DEFINE("_SHOP_ITEMINFO4",    			    "");
DEFINE("_SHOP_ITEMINFO5",    			    "");
DEFINE("_SHOP_ITEMINFO6",    			    "");
DEFINE("_SHOP_ITEMINFO7",    			    "");
DEFINE("_SHOP_ITEMINFO8",    			    "");
DEFINE("_SHOP_ITEMINFO9",    			    "");
DEFINE("_SHOP_ITEMINFO10",    			    "");
DEFINE("_SHOP_ITEMINFO11",    			    "");
DEFINE("_SHOP_ITEMINFO12",    			    "");
DEFINE("_SHOP_ITEMINFO13",    			    "");
DEFINE("_SHOP_ITEMINFO14",    			    "");
DEFINE("_SHOP_ITEMINFO15",    			    "");
DEFINE("_SHOP_ITEMINFO16",    			    "");
DEFINE("_SHOP_ITEMINFO17",    			    "");
DEFINE("_SHOP_ITEMINFO18",    			    "Със сателит можеш да следиш местоположението на конкретен мафиот.");
DEFINE("_SHOP_ITEMINFO19",    			    "От спътника можеш да гледаш кой къде се намира в момента.");
DEFINE("_SHOP_ITEMINFO20",    			    "Започнете легален бизнес. Отворете верига от кафенета и получавайте по 500 € на час.");
DEFINE("_SHOP_ITEMINFO21",    			    "Сейфът ще пази парите ви на сигурно място дори и да ви нападнат или убият,<br>никой от другите мафиоти неможе да вижда колко пари има в сейфа,<br> а всеки сейф събира по 50 милиона за които не получаваш лихва.");
DEFINE("_SHOP_ITEMINFO22",    			    "Хубавото на Швейцарските банки е това че цялата информация за сметките е тайна<br>Ако си направиш сметка там ще можеш да депозираш по 5 милиона и да <br>теглиш 50 милиона евро на ден. Лихвата на ден е 2%.");
DEFINE("_SHOP_ITEMINFO23",    			    "Трябват ти само 5 точки за атака за да можеш да нападаш другите мафиоти.");
DEFINE("_SHOP_ITEMINFO24",    			    "Отвори си банкова сметка в някоя банка и извършвай легални транзакции на пари.");
DEFINE("_SHOP_ITEMINFO25",    			    "Изплашен си? Купи си защита от мафията и спи спокойно. <br>На разположение са 24 часова защита от <br> специални единици на армията.");
?>